service: lambda-bedrock-proxy
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 'bedrock:*'
          Resource: '*'
  apiGateway:
    apiKeys:
      - name: tollmkey
        description: tollmkey api key# Optional
    usagePlan:
      quota:
        limit: 5
        offset: 2
        period: MONTH
      throttle:
        burstLimit: 200
        rateLimit: 100

layers:
  bedrock:
    name: bedrock-dependencies
    path: layers/tools
    compatibleRuntimes:
      - python3.11
    description: "Dependencies bedrock"

package:
  include:
    - src/handler.py
    - src/client_bedrock.py
  exclude:
    - node_modules/**
    - venv/**

functions:
  hello:
    handler: src/handler.hello
    timeout: 30
    events:
      - http:
          path: titan
          method: get
          private: true
    layers:
      - !Ref BedrockLambdaLayer